### ISSUE TITLE
does --common work?

### ISSUE THREAD

**Issue by jegpeek** [dfm/wordle#1]
I don't know rust syntax, but I have tried a lot of combinations and can't get --common to work. What is a call that uses --common that works?

**Comment by dfm** [comment]
It works fine for me! Perhaps you're forgetting the `--`? E.g. to simulate a solution for `query` restricted to common words, you would run:

```bash
cargo run -- --common -s query
```

**Comment by dfm** [comment]
If not, what error are you seeing?

**Comment by jegpeek** [comment]
could have sworn a used that syntax! Works great, thanks!
